---

- name: Ensuring that administration group is present
  group:
    name: "{{ groups__admin_group }}"
    state: present

- name: Ensuring that administration group is able to use sudo without password
  lineinfile:
    dest: "/etc/sudoers.d/{{ groups__admin_group }}"
    line: "%{{ groups__admin_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
