---

- name: Add a docker Apt signing key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add a docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/raspbian/ {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Keep docker-ce and docker-compose packages in latest version
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    install_recommends: no
  with_items:
    - docker-ce
    - docker-compose
